on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: A tag for the docs artifact
        required: true

jobs:
  build_new_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PtyPy Code
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
          check-latest: true

      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: mpich

      - name: Install Sphinx
        run: pip install sphinx myst_parser

      - name: Install PtyPy
        run: pip install .[full]

      - name: Install docs dependencies
        run: pip install -r docs/requirements.txt

      - name: Set Path to Sphinx Build
        run: echo "SPHINXBUILD=`which sphinx-build`" >> $GITHUB_ENV

      - name: Checkout PtyPy Tutorials
        uses: actions/checkout@v7
        with:
          repository: ptycho/tutorials
          path: tutorials
          ref: main

      - name: Convert Notebooks
        working-directory: tutorials
        run: |
          mv notebooks docs/
          python docs/scripts/convert.py --actions

      - name: Set Path to Tutorial Notebooks
        run: echo "PTYPY_PATH_TO_NOTEBOOKS=`readlink -e ./tutorials/docs/notebooks`" >> $GITHUB_ENV

      - name: Build Sphinx Documentation
        working-directory: docs
        run: make html
        env:
          PTYPY_BUILD_LEGACY_TUTORIALS: 1
          PTYPY_BUILD_PARAM_TREE: 1
          PTYPY_BUILD_USERGUIDE_IMAGES: 1
          PTYPY_BUILD_NOTEBOOK_TUTORIALS: 1

      - name: Rename Build Directory
        run: |
          mkdir artifacts
          mv docs/_build/html artifacts/${{ inputs.tag }}
          
      - name: Upload Docs Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: docs-${{ inputs.tag }}
          path: artifacts
